simulation:
    L: 64
    ngrids_factor: 4
    threads_per_block: 32
    nsweeps: 100000

sig:
    ngrids: 512

comm:
    nsweeps: 2000
    ngrids: 4096

parameters:
    beta: 0.474   # inverse temperature
    h: 0.01     # external field 

output:
    grid_output_int: 100   # multiple of mag_output_int
    mag_output_int: 100    # frequency for CV computation

collective_variable:
    type: "largest_cluster"
    up_threshold: 2500
    dn_threshold: 19.5

paths:
    gridstates: "data/gridstates_{parameters[beta]:.3f}_{parameters[h]:.3f}.hdf5"
    training: "data/gridstates_training_{parameters[beta]:.3f}_{parameters[h]:.3f}.hdf5"
    plot_dir: "figures"
    save_dir: "data"

analyse:
    bins: 100
    cluster_min: 0
    cluster_max: 400
    bin_per_cluster: true   # if true, each cluster size gets one bin
    cluster_vlines: 20
    magnetization_xtick_step: 0.1

gpu:
    sm_mult: 4
    tasks: 10
